apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      serviceAccountName: console-sa
      containers:
        - name: console
          image: minio/console:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: CONSOLE_OPERATOR_MODE
              value: "on"
          args:
            - /console
            - server
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9433
              name: https
