---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: default
  labels:
    name: console
spec:
  ports:
    - port: 9090
      name: http
    - port: 9443
      name: https
  selector:
    app: console-standalone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-standalone
  template:
    metadata:
      labels:
        app: console-standalone
    spec:
      containers:
        - name: console
          image: 'minio/console:v0.15.9'
          imagePullPolicy: "IfNotPresent"
          env:
            - name: CONSOLE_MINIO_SERVER
              value: "https://minio.default.svc.cluster.local"
          args:
            - server
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9433
              name: https
